# -----------------------------------------------------------------------------
# DEPLOYMENT 2: Medium instance (512Mi RAM, 250m CPU)
# -----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-medium
spec:
  selector:
    matchLabels:
      app: python-api
      size: medium
  template:
    metadata:
      labels:
        app: python-api
        size: medium
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: python-api-container
        image: sample_api
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: shared-data
          mountPath: /app/data
        imagePullPolicy: Never
        resources:
          requests:
            memory: "1Gi"
            cpu: "125m"
          limits:
            memory: "2Gi"
            cpu: "250m"
      volumes:
      - name: shared-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: python-api-medium-svc
spec:
  selector:
    app: python-api
    size: medium
  ports:
  - name: api
    port: 8000
    targetPort: 8000
  - name: metrics
    port: 9000
    targetPort: 9000